### ISSUE TITLE
Those folders should not be in the repository

### ISSUE THREAD

**Issue by incredibleLeitman** [andulica/QuizzMaker#1]
<img width="157" alt="Screenshot 2023-08-01 at 11 29 14" src="https://github.com/andulica/QuizzMaker/assets/24638443/fa972c34-6ed5-4ecd-80d1-3a30aba12cdc">

Because they are generated each time the program gets compiled

**Comment by andulica** [comment]
Issue solved by deleting them and moving to the git ignore section
