### ISSUE TITLE
Let user choose the amount of answers?

### ISSUE THREAD

**Issue by mayisa87** [andulica/QuizzMaker#13]
https://github.com/andulica/QuizzMaker/blob/68d147d7098b4118f109b3b2e4d1ae11303ba17f/GUI.cs#L81

Currently your array ha a fixed number of answers, would about to ask user how many answers the question would have?

**Comment by andulica** [comment]
It made more sense to me to ask user to enter a specified number of answers to create some sort of standard of the way the questions are built. Would be better to implement a function that gives user control to set the number of answers he can enter?

**Comment by mayisa87** [comment]
Ok, I see what you mean. Five answers seem a bit much for me, that's why I had the feeling,  having the possibility to choose how much anwsers to enter would be better.
What avout giving user option to enter between 3 to 5 answers? 

I just made the experience as I created some quizes in past, that it is quite hard to always finde so much answers 😅😅😅
