### ISSUE TITLE
If possible, avoid crossing calls

### ISSUE THREAD

**Issue by mayisa87** [andulica/QuizzMaker#24]
Currently you call SelectQuizToPlay in your Program.cs and then call in there again a method of the Program.cs

https://github.com/andulica/QuizzMaker/blob/9afbb03821f1ac79f54c2e33b6cfdf0fb00c39d2/QuizEditor.cs#L11
As the method is already named "selectQuizToPlay", 

Instead of do a call back on the Program.cs. use the List<> as return value and return it to the Program.cs Main method.
https://github.com/andulica/QuizzMaker/blob/9afbb03821f1ac79f54c2e33b6cfdf0fb00c39d2/QuizEditor.cs#L20

I would suggest that you store the current List, so your current quizData into a field and after calling SelectQuizToPlay, immediately call the method PlayQuestionsFromFile. If you store the List returned as a field, you can even get rid of the parameter in your PlayQuestionsFromFile method :)

**Comment by andulica** [comment]
I am a bit confused and I don't understand what you are asking me to do. Can you give more details please?
