### ISSUE TITLE
Game score not right?

### ISSUE THREAD

**Issue by mayisa87** [andulica/QuizzMaker#29]
![image](https://github.com/andulica/QuizzMaker/assets/130921606/3460416d-4f98-439a-9433-c1fe63aa3899)

I added and played a game. I answered the question correctly, got 2 correct answers entered and guessed them right. I got the info that I guessed right, but the game score seems not to be right yet.

**Comment by andulica** [comment]
I replicated the same scenario as your one and it works as it should. The score is getting incremented by 1 whenever you answer correct to a question. So if a questions has 2 correct answers and you found both answers that means your score will be incremented just by 1. Hope that it makes sense, if not please let me know
