### ISSUE TITLE
Does this need to be a public function that can be called from outside?

### ISSUE THREAD

**Issue by incredibleLeitman** [andulica/QuizzMaker#3]
https://github.com/andulica/QuizzMaker/blob/f1206f7f7d240ea391d5e83d563983a89b94376e/GUI.cs#L87
I think it would make your code in main cleaner if this function would be called directly inside the function that prints your welcome message than from outside

**Comment by andulica** [comment]
Method deleted for not being too useful at this stage. Will focus on UX later in the process
