### ISSUE TITLE
Take care for unused usings and remove then regularly

### ISSUE THREAD

**Issue by incredibleLeitman** [andulica/QuizzMaker#4]
https://github.com/andulica/QuizzMaker/blob/f1206f7f7d240ea391d5e83d563983a89b94376e/Program.cs#L2
You can either get into the habit of cleaning your usings regularly or at least double check them before each commit

**Comment by andulica** [comment]
Issue solved. Also I can see that is not shortcut for removing unused usings. Is it a way to add custom shortcuts?

**Comment by incredibleLeitman** [comment]
There should be if you are using Visual Studio 🤔 
https://course.raketementoring.com/courses/rakete-mentoring/lectures/45560205?preview=admin
