### ISSUE TITLE
Redactor to use TakeUserInput(min,max)?

### ISSUE THREAD

**Issue by mayisa87** [andulica/QuizzMaker#8]
https://github.com/andulica/QuizzMaker/blob/903a43ba47312741619d35053e42185038bfc6ae/GUI.cs#L61

The TskeUserInput(min,max) and TakeUserInput(max) do nearly the same.

You could just call TakeUserInput(1,max); in TakeUserInput(max) and avoid duplicated code

**Comment by andulica** [comment]
True. I just thought that method overloading would be a good solution

**Comment by mayisa87** [comment]
It is! Really cool that you do it like this. And you can still have the overloaded version, but by calling TakeUserInput(1,max) you can avoid quite a lot of duplicated code
