### ISSUE TITLE
Why not using a simple list for answers?

### ISSUE THREAD

**Issue by mayisa87** [andulica/QuizzMaker#9]
https://github.com/andulica/QuizzMaker/blob/903a43ba47312741619d35053e42185038bfc6ae/GUI.cs#L110

Why did you go for string[] and not List<String>? You could just add the entries to list

**Comment by andulica** [comment]
I thought that a List is too complex for this use.

**Comment by mayisa87** [comment]
No, but as I wrote, if you like to use array, that's also a way to do it

**Comment by andulica** [comment]
So I guess that won't be any benefits of using either a List or a string[] in this situation and we can close the issue or should I go and implement your suggestion?

**Comment by mayisa87** [comment]
Let's close it :)
